{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default (include "dandelion.fullname" .) .Values.serviceAccount.name }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "dandelion.fullname" . }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "dandelion.fullname" . }}
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: {{ default (include "dandelion.fullname" .) .Values.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "dandelion.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
